<?php

use App\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $perms = config('perm');

        $permissions = [
            ['name' => $perms['listWaitingMember'], 'module' => 'Dashboard'],
            ['name' => $perms['approveMember'], 'module' => 'Dashboard'],
            ['name' => $perms['rejectMember'], 'module' => 'Dashboard'],
            ['name' => $perms['listMemberReq'], 'module' => 'Membership Request'],
            ['name' => $perms['approveMemberReq'], 'module' => 'Membership Request'],
            ['name' => $perms['rejectMemberReq'], 'module' => 'Membership Request'],
            ['name' => $perms['pendingMemberReq'], 'module' => 'Membership Request'],
            ['name' => $perms['commentMemberReq'], 'module' => 'Membership Request'],
            ['name' => $perms['listClaim'], 'module' => 'Business Claim Request'],
            ['name' => $perms['approveClaim'], 'module' => 'Business Claim Request'],
            ['name' => $perms['rejectClaim'], 'module' => 'Business Claim Request'],
            ['name' => $perms['viewDocClaim'], 'module' => 'Business Claim Request'],
            ['name' => $perms['listUser'], 'module' => 'User'],
            ['name' => $perms['addUser'], 'module' => 'User'],
            ['name' => $perms['editUser'], 'module' => 'User'],
            ['name' => $perms['deleteUser'], 'module' => 'User'],
            ['name' => $perms['hardDeleteUser'], 'module' => 'User'],
            ['name' => $perms['activateUser'], 'module' => 'User'],
            ['name' => $perms['manageBusiness'], 'module' => 'User'],
            ['name' => $perms['listOTP'], 'module' => 'OTP'],
            ['name' => $perms['sendOTP'], 'module' => 'OTP'],
            ['name' => $perms['editOTP'], 'module' => 'OTP'],
            ['name' => $perms['deleteOTP'], 'module' => 'OTP'],
            ['name' => $perms['listResetPwdOTP'], 'module' => 'OTP'],
            ['name' => $perms['listEntity'], 'module' => 'Entity'],
            ['name' => $perms['addEntity'], 'module' => 'Entity'],
            ['name' => $perms['editEntity'], 'module' => 'Entity'],
            ['name' => $perms['viewEntity'], 'module' => 'Entity'],
            ['name' => $perms['deleteEntity'], 'module' => 'Entity'],
            ['name' => $perms['approveEntity'], 'module' => 'Entity'],
            ['name' => $perms['listPremiumEntity'], 'module' => 'Entity'],
            ['name' => $perms['listPromotedEntity'], 'module' => 'Entity'],
            ['name' => $perms['csvImport'], 'module' => 'Entity'],
            ['name' => $perms['manageService'], 'module' => 'Entity'],
            ['name' => $perms['addService'], 'module' => 'Entity'],
            ['name' => $perms['editService'], 'module' => 'Entity'],
            ['name' => $perms['deleteService'], 'module' => 'Entity'],
            ['name' => $perms['manageProduct'], 'module' => 'Entity'],
            ['name' => $perms['addProduct'], 'module' => 'Entity'],
            ['name' => $perms['editProduct'], 'module' => 'Entity'],
            ['name' => $perms['deleteProduct'], 'module' => 'Entity'],
            ['name' => $perms['manageOwner'], 'module' => 'Entity'],
            ['name' => $perms['addOwner'], 'module' => 'Entity'],
            ['name' => $perms['editOwner'], 'module' => 'Entity'],
            ['name' => $perms['deleteOwner'], 'module' => 'Entity'],
            ['name' => $perms['manageMembership'], 'module' => 'Entity'],
            ['name' => $perms['addMembership'], 'module' => 'Entity'],
            ['name' => $perms['editMembership'], 'module' => 'Entity'],
            ['name' => $perms['deleteMembership'], 'module' => 'Entity'],
            ['name' => $perms['updateStatusMembership'], 'module' => 'Entity'],
            ['name' => $perms['manageWebsite'], 'module' => 'Entity'],
            ['name' => $perms['sendWhatsapp'], 'module' => 'Entity'],
            ['name' => $perms['listAssetType'], 'module' => 'Asset Type'],
            ['name' => $perms['addAssetType'], 'module' => 'Asset Type'],
            ['name' => $perms['listSubAsset'], 'module' => 'Asset Type'],
            ['name' => $perms['addSubAsset'], 'module' => 'Asset Type'],
            ['name' => $perms['editSubAsset'], 'module' => 'Asset Type'],
            ['name' => $perms['deleteSubAsset'], 'module' => 'Asset Type'],
            ['name' => $perms['listReason'], 'module' => 'Reason'],
            ['name' => $perms['addReason'], 'module' => 'Reason'],
            ['name' => $perms['editReason'], 'module' => 'Reason'],
            ['name' => $perms['deleteReason'], 'module' => 'Reason'],
            ['name' => $perms['listAdvertise'], 'module' => 'Advertise'],
            ['name' => $perms['addAdvertise'], 'module' => 'Advertise'],
            ['name' => $perms['editAdvertise'], 'module' => 'Advertise'],
            ['name' => $perms['deleteAdvertise'], 'module' => 'Advertise'],
            ['name' => $perms['listSearchTerm'], 'module' => 'Search Term'],
            ['name' => $perms['listPublicWebsite'], 'module' => 'Public Website'],
            ['name' => $perms['addPublicWebsite'], 'module' => 'Public Website'],
            ['name' => $perms['editPublicWebsite'], 'module' => 'Public Website'],
            ['name' => $perms['deletePublicWebsite'], 'module' => 'Public Website'],
            ['name' => $perms['updateStatusPublicWebsite'], 'module' => 'Public Website'],
            ['name' => $perms['listPublicWebsiteTemplate'], 'module' => 'Public Website Template'],
            ['name' => $perms['addPublicWebsiteTemplate'], 'module' => 'Public Website Template'],
            ['name' => $perms['editPublicWebsiteTemplate'], 'module' => 'Public Website Template'],
            ['name' => $perms['deletePublicWebsiteTemplate'], 'module' => 'Public Website Template'],
            ['name' => $perms['updateStatusPublicWebsiteTemplate'], 'module' => 'Public Website Template'],
            ['name' => $perms['listPublicWebsitePlan'], 'module' => 'Public Website Plan'],
            ['name' => $perms['addPublicWebsitePlan'], 'module' => 'Public Website Plan'],
            ['name' => $perms['editPublicWebsitePlan'], 'module' => 'Public Website Plan'],
            ['name' => $perms['deletePublicWebsitePlan'], 'module' => 'Public Website Plan'],
            ['name' => $perms['updateStatusPublicWebsitePlan'], 'module' => 'Public Website Plan'],
            ['name' => $perms['listPublicWebsitePayments'], 'module' => 'Public Website Payments'],
            ['name' => $perms['addPublicWebsitePayments'], 'module' => 'Public Website Payments'],
            ['name' => $perms['editPublicWebsitePayments'], 'module' => 'Public Website Payments'],
            ['name' => $perms['deletePublicWebsitePayments'], 'module' => 'Public Website Payments'],
            ['name' => $perms['listPublicWebsiteInquiry'], 'module' => 'Public Website Inquiry'],
            ['name' => $perms['listPublicWebsiteReview'], 'module' => 'Public Website Review'],
            ['name' => $perms['listMarketplaceAds'], 'module' => 'Marketplace Ads'],
            ['name' => $perms['editMarketplaceAds'], 'module' => 'Marketplace Ads'],
            ['name' => $perms['deleteMarketplaceAds'], 'module' => 'Marketplace Ads'],
            ['name' => $perms['approveMarketplaceAds'], 'module' => 'Marketplace Ads'],
            ['name' => $perms['rejectMarketplaceAds'], 'module' => 'Marketplace Ads'],
            ['name' => $perms['restoreMarketplaceAds'], 'module' => 'Marketplace Ads'],
            ['name' => $perms['listCategory'], 'module' => 'Category'],
            ['name' => $perms['addCategory'], 'module' => 'Category'],
            ['name' => $perms['editCategory'], 'module' => 'Category'],
            ['name' => $perms['deleteCategory'], 'module' => 'Category'],
            ['name' => $perms['listSubCategory'], 'module' => 'Category'],
            ['name' => $perms['addSubCategory'], 'module' => 'Category'],
            ['name' => $perms['editSubCategory'], 'module' => 'Category'],
            ['name' => $perms['deleteSubCategory'], 'module' => 'Category'],
            ['name' => $perms['listTrending'], 'module' => 'Category'],
            ['name' => $perms['updateStatusTrending'], 'module' => 'Category'],
            ['name' => $perms['listTrendingService'], 'module' => 'Trending Service'],
            ['name' => $perms['updateStatusTrendingService'], 'module' => 'Trending Service'],
            ['name' => $perms['listRepresentativeRequests'], 'module' => 'Representative Requests'],
            ['name' => $perms['approveRepresentativeRequests'], 'module' => 'Representative Requests'],
            ['name' => $perms['rejectRepresentativeRequests'], 'module' => 'Representative Requests'],
            ['name' => $perms['listMembershipPlan'], 'module' => 'Membership Plan'],
            ['name' => $perms['addMembershipPlan'], 'module' => 'Membership Plan'],
            ['name' => $perms['editMembershipPlan'], 'module' => 'Membership Plan'],
            ['name' => $perms['deleteMembershipPlan'], 'module' => 'Membership Plan'],
            ['name' => $perms['listEmailTemplate'], 'module' => 'Email Template'],
            ['name' => $perms['addEmailTemplate'], 'module' => 'Email Template'],
            ['name' => $perms['editEmailTemplate'], 'module' => 'Email Template'],
            ['name' => $perms['deleteEmailTemplate'], 'module' => 'Email Template'],
            ['name' => $perms['listSendEmail'], 'module' => 'Send Email'],
            ['name' => $perms['addSendEmail'], 'module' => 'Send Email'],
            ['name' => $perms['editSendEmail'], 'module' => 'Send Email'],
            ['name' => $perms['deleteSendEmail'], 'module' => 'Send Email'],
            ['name' => $perms['listCountry'], 'module' => 'Country'],
            ['name' => $perms['addCountry'], 'module' => 'Country'],
            ['name' => $perms['editCountry'], 'module' => 'Country'],
            ['name' => $perms['deleteCountry'], 'module' => 'Country'],
            ['name' => $perms['listState'], 'module' => 'State'],
            ['name' => $perms['addState'], 'module' => 'State'],
            ['name' => $perms['editState'], 'module' => 'State'],
            ['name' => $perms['deleteState'], 'module' => 'State'],
            ['name' => $perms['listCity'], 'module' => 'City'],
            ['name' => $perms['addCity'], 'module' => 'City'],
            ['name' => $perms['editCity'], 'module' => 'City'],
            ['name' => $perms['deleteCity'], 'module' => 'City'],
            ['name' => $perms['listNotification'], 'module' => 'Notification'],
            ['name' => $perms['listWaitingNotification'], 'module' => 'Notification'],
            ['name' => $perms['listHistoryNotification'], 'module' => 'Notification'],
            ['name' => $perms['saveNotification'], 'module' => 'Notification'],
            ['name' => $perms['sendNotification'], 'module' => 'Notification'],
            ['name' => $perms['approveNotification'], 'module' => 'Notification'],
            ['name' => $perms['rejectNotification'], 'module' => 'Notification'],
            ['name' => $perms['listCms'], 'module' => 'CMS'],
            ['name' => $perms['addCms'], 'module' => 'CMS'],
            ['name' => $perms['editCms'], 'module' => 'CMS'],
            ['name' => $perms['deleteCms'], 'module' => 'CMS'],
            ['name' => $perms['listNewsletter'], 'module' => 'Newsletter'],
            ['name' => $perms['addNewsletter'], 'module' => 'Newsletter'],
            ['name' => $perms['editNewsletter'], 'module' => 'Newsletter'],
            ['name' => $perms['deleteNewsletter'], 'module' => 'Newsletter'],
            ['name' => $perms['sendNewsletter'], 'module' => 'Newsletter'],
            ['name' => $perms['listBranding'], 'module' => 'Branding'],
            ['name' => $perms['addBranding'], 'module' => 'Branding'],
            ['name' => $perms['deleteBranding'], 'module' => 'Branding'],
            ['name' => $perms['createGroupBranding'], 'module' => 'Branding'],
            ['name' => $perms['listPaymentTransaction'], 'module' => 'Payment Transaction'],
            ['name' => $perms['listAdvisors'], 'module' => 'Advisors'],
            ['name' => $perms['addAdvisors'], 'module' => 'Advisors'],
            ['name' => $perms['editAdvisors'], 'module' => 'Advisors'],
            ['name' => $perms['deleteAdvisors'], 'module' => 'Advisors'],
            ['name' => $perms['listPost'], 'module' => 'Post'],
            ['name' => $perms['addPost'], 'module' => 'Post'],
            ['name' => $perms['editPost'], 'module' => 'Post'],
            ['name' => $perms['deletePost'], 'module' => 'Post'],
            ['name' => $perms['listOnlineStore'], 'module' => 'Online Store'],
            ['name' => $perms['addOnlineStore'], 'module' => 'Online Store'],
            ['name' => $perms['editOnlineStore'], 'module' => 'Online Store'],
            ['name' => $perms['deleteOnlineStore'], 'module' => 'Online Store'],
            ['name' => $perms['listSetting'], 'module' => 'Setting'],
            ['name' => $perms['editSetting'], 'module' => 'Setting'],
            ['name' => $perms['viewSiteSetting'], 'module' => 'Setting'],
            ['name' => $perms['viewAdminSetting'], 'module' => 'Setting'],
            ['name' => $perms['listRole'], 'module' => 'Role'],
            ['name' => $perms['addRole'], 'module' => 'Role'],
            ['name' => $perms['editRole'], 'module' => 'Role'],
            ['name' => $perms['deleteRole'], 'module' => 'Role'],
            ['name' => $perms['listPermission'], 'module' => 'Permission'],
            ['name' => $perms['addPermission'], 'module' => 'Permission'],
            ['name' => $perms['editPermission'], 'module' => 'Permission'],
            ['name' => $perms['deletePermission'], 'module' => 'Permission'],
            ['name' => $perms['listReport'], 'module' => 'Report'],
            ['name' => $perms['viewReport'], 'module' => 'Report'],
            ['name' => $perms['editReport'], 'module' => 'Report'],
            ['name' => $perms['deleteReport'], 'module' => 'Report'],
            ['name' => $perms['listSite'], 'module' => 'Site'],
            ['name' => $perms['viewSite'], 'module' => 'Site'],
            ['name' => $perms['addSite'], 'module' => 'Site'],
            ['name' => $perms['editSite'], 'module' => 'Site'],
            ['name' => $perms['deleteSite'], 'module' => 'Site'],
            ['name' => $perms['approveSite'], 'module' => 'Site'],
            ['name' => $perms['rejectSite'], 'module' => 'Site'],
            ['name' => $perms['deleteMemberSite'], 'module' => 'Site'],
            ['name' => $perms['listNotInUse'], 'module' => 'Not In Use'],

            ['name' => $perms['listLocation'], 'module' => 'Location'],
            ['name' => $perms['addLocation'], 'module' => 'Location'],
            ['name' => $perms['editLocation'], 'module' => 'Location'],
            ['name' => $perms['deleteLocation'], 'module' => 'Location'],
            ['name' => $perms['listApplication'], 'module' => 'Application'],
            ['name' => $perms['addApplication'], 'module' => 'Application'],
            ['name' => $perms['editApplication'], 'module' => 'Application'],
            ['name' => $perms['deleteApplication'], 'module' => 'Application'], 
            ['name' => $perms['listCallToAction'], 'module' => 'CallToAction'],
            ['name' => $perms['addCallToAction'], 'module' => 'CallToAction'],
            ['name' => $perms['editCallToAction'], 'module' => 'CallToAction'],
            ['name' => $perms['deleteCallToAction'], 'module' => 'CallToAction'],

            ['name' => $perms['listJobs'], 'module' => 'Jobs'],
            ['name' => $perms['addJobs'], 'module' => 'Jobs'],
            ['name' => $perms['editJobs'], 'module' => 'Jobs'],
            ['name' => $perms['deleteJobs'], 'module' => 'Jobs'],

            ['name' => $perms['listJobApply'], 'module' => 'Job Apply List'],
        ];

        foreach ($permissions as $permission) {
            Permission::updateOrCreate(['name' => $permission['name']], $permission);
        }
    }
}
